# -*- coding: utf-8 -*-
"""Evidencia2_RepositorioGithub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NZKUcwpnxk4KFR4ip1xLm5Mh1_6ZPLbA
"""

class Estudiante:
    def __init__(self, nombre, edad):
        self._nombre = nombre
        self._edad = edad

    @property
    def nombre(self):
        return self._nombre

    @nombre.setter
    def nombre(self, nuevo_nombre):
        self._nombre = nuevo_nombre

    @property
    def edad(self):
        return self._edad

    @edad.setter
    def edad(self, nueva_edad):
        self._edad = nueva_edad

    def presentarse(self):
        return f"Hola, mi nombre es {self._nombre} y tengo {self._edad} años."

#Crear un objeto de la clase Estudiante
estudiante = Estudiante("Juan", 20)

#Acceder a los atributos del objeto
print(estudiante.nombre)  # Salida: Juan
print(estudiante.edad)  # Salida: 20

#Modificar los atributos del objeto
estudiante.nombre = "Pedro"
estudiante.edad = 21

#Verificar que los atributos se han modificado correctamente
print(estudiante.nombre)  #Salida: Pedro
print(estudiante.edad)  #Salida: 21

#Usar el método de la clase
print(estudiante.presentarse())  #Salida: Hola, mi nombre es Pedro y tengo 21 años.